// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function GetChats():Promise<Array<model.ChatSummary>>;

export function GetMessages(arg1:string):Promise<Array<model.Message>>;

export function LoadFile(arg1:string):Promise<main.LoadResult>;

export function OpenFileDialog():Promise<main.LoadResult>;

export function Search(arg1:string):Promise<Array<model.SearchResult>>;
